// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SistemAdminProducts.Models.Context;

#nullable disable

namespace SistemAdminProducts.Migrations
{
    [DbContext(typeof(ApplicationDdContext))]
    partial class ApplicationDdContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SistemAdminProducts.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreateAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateTime>("UpdateAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Category");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreateAt = new DateTime(2023, 6, 4, 18, 33, 6, 445, DateTimeKind.Local).AddTicks(93),
                            Description = "Description Category 1",
                            Name = "Category 1",
                            UpdateAt = new DateTime(2023, 6, 4, 18, 33, 6, 445, DateTimeKind.Local).AddTicks(94)
                        },
                        new
                        {
                            Id = 2,
                            CreateAt = new DateTime(2023, 6, 4, 18, 33, 6, 445, DateTimeKind.Local).AddTicks(96),
                            Description = "Description Category 2",
                            Name = "Category 2",
                            UpdateAt = new DateTime(2023, 6, 4, 18, 33, 6, 445, DateTimeKind.Local).AddTicks(97)
                        },
                        new
                        {
                            Id = 3,
                            CreateAt = new DateTime(2023, 6, 4, 18, 33, 6, 445, DateTimeKind.Local).AddTicks(98),
                            Description = "Description Category 3",
                            Name = "Category 3",
                            UpdateAt = new DateTime(2023, 6, 4, 18, 33, 6, 445, DateTimeKind.Local).AddTicks(99)
                        });
                });

            modelBuilder.Entity("SistemAdminProducts.Models.Products", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CategoryId")
                        .HasColumnType("int");

                    b.Property<double>("CostPrice")
                        .HasColumnType("float");

                    b.Property<DateTime>("CreateAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<double>("Proffit")
                        .HasColumnType("float");

                    b.Property<int>("SubCategoryId")
                        .HasColumnType("int");

                    b.Property<int>("SupplierId")
                        .HasColumnType("int");

                    b.Property<string>("UpcCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("UpdateAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("Description")
                        .IsUnique();

                    b.HasIndex("SubCategoryId");

                    b.HasIndex("SupplierId");

                    b.HasIndex("UpcCode")
                        .IsUnique();

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CostPrice = 10.5,
                            CreateAt = new DateTime(2023, 6, 4, 18, 33, 6, 445, DateTimeKind.Local).AddTicks(354),
                            Description = "Product 1",
                            Proffit = 1.5,
                            SubCategoryId = 1,
                            SupplierId = 1,
                            UpcCode = "4314556",
                            UpdateAt = new DateTime(2023, 6, 4, 18, 33, 6, 445, DateTimeKind.Local).AddTicks(355)
                        },
                        new
                        {
                            Id = 2,
                            CostPrice = 10.5,
                            CreateAt = new DateTime(2023, 6, 4, 18, 33, 6, 445, DateTimeKind.Local).AddTicks(358),
                            Description = "Product 2",
                            Proffit = 1.5,
                            SubCategoryId = 2,
                            SupplierId = 2,
                            UpcCode = "31467885",
                            UpdateAt = new DateTime(2023, 6, 4, 18, 33, 6, 445, DateTimeKind.Local).AddTicks(359)
                        },
                        new
                        {
                            Id = 3,
                            CostPrice = 10.5,
                            CreateAt = new DateTime(2023, 6, 4, 18, 33, 6, 445, DateTimeKind.Local).AddTicks(361),
                            Description = "Product 3",
                            Proffit = 1.5,
                            SubCategoryId = 3,
                            SupplierId = 3,
                            UpcCode = "12345623",
                            UpdateAt = new DateTime(2023, 6, 4, 18, 33, 6, 445, DateTimeKind.Local).AddTicks(361)
                        });
                });

            modelBuilder.Entity("SistemAdminProducts.Models.SubCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreateAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateTime>("UpdateAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("SubCategory");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            CreateAt = new DateTime(2023, 6, 4, 18, 33, 6, 445, DateTimeKind.Local).AddTicks(298),
                            Description = "Description SubCategory 1",
                            Name = "SubCategory 1",
                            UpdateAt = new DateTime(2023, 6, 4, 18, 33, 6, 445, DateTimeKind.Local).AddTicks(300)
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 2,
                            CreateAt = new DateTime(2023, 6, 4, 18, 33, 6, 445, DateTimeKind.Local).AddTicks(302),
                            Description = "Description SubCategory 2",
                            Name = "SubCategory 2",
                            UpdateAt = new DateTime(2023, 6, 4, 18, 33, 6, 445, DateTimeKind.Local).AddTicks(302)
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 3,
                            CreateAt = new DateTime(2023, 6, 4, 18, 33, 6, 445, DateTimeKind.Local).AddTicks(304),
                            Description = "Description SubCategory 3",
                            Name = "SubCategory 3",
                            UpdateAt = new DateTime(2023, 6, 4, 18, 33, 6, 445, DateTimeKind.Local).AddTicks(305)
                        });
                });

            modelBuilder.Entity("SistemAdminProducts.Models.Supplier", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("CreateAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Phone")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateTime>("UpdateAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Suppliers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreateAt = new DateTime(2023, 6, 4, 18, 33, 6, 445, DateTimeKind.Local).AddTicks(327),
                            Name = "Supplier 1",
                            UpdateAt = new DateTime(2023, 6, 4, 18, 33, 6, 445, DateTimeKind.Local).AddTicks(328)
                        },
                        new
                        {
                            Id = 2,
                            CreateAt = new DateTime(2023, 6, 4, 18, 33, 6, 445, DateTimeKind.Local).AddTicks(329),
                            Name = "Supplier 2",
                            UpdateAt = new DateTime(2023, 6, 4, 18, 33, 6, 445, DateTimeKind.Local).AddTicks(330)
                        },
                        new
                        {
                            Id = 3,
                            CreateAt = new DateTime(2023, 6, 4, 18, 33, 6, 445, DateTimeKind.Local).AddTicks(331),
                            Name = "Supplier 3",
                            UpdateAt = new DateTime(2023, 6, 4, 18, 33, 6, 445, DateTimeKind.Local).AddTicks(331)
                        });
                });

            modelBuilder.Entity("SistemAdminProducts.Models.Products", b =>
                {
                    b.HasOne("SistemAdminProducts.Models.Category", null)
                        .WithMany("Products")
                        .HasForeignKey("CategoryId");

                    b.HasOne("SistemAdminProducts.Models.SubCategory", "SubCategory")
                        .WithMany("Products")
                        .HasForeignKey("SubCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SistemAdminProducts.Models.Supplier", "Supplier")
                        .WithMany("Products")
                        .HasForeignKey("SupplierId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SubCategory");

                    b.Navigation("Supplier");
                });

            modelBuilder.Entity("SistemAdminProducts.Models.SubCategory", b =>
                {
                    b.HasOne("SistemAdminProducts.Models.Category", "Category")
                        .WithMany("SubCategories")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("SistemAdminProducts.Models.Category", b =>
                {
                    b.Navigation("Products");

                    b.Navigation("SubCategories");
                });

            modelBuilder.Entity("SistemAdminProducts.Models.SubCategory", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("SistemAdminProducts.Models.Supplier", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
